### ISSUE TITLE
Manage All PropTypes...

### ISSUE THREAD

**Issue by bpetetot** [Zenika/hoc-react-datgui#6]

**Comment by fabienjuif** [comment]
And create an 'else' case that said which PropTypes is not understood (into console)

**Comment by bpetetot** [comment]
PropTypes cases can be resolved : 
- [x] `array` => `array`
- [x] `bool` => `boolean`
- [x] `func` => `function`
- [x] `number` =>  `number`
- [x] `object` => `object`
- [x] `string` => `string`
- [ ] `symbol` => `string`
- [x] `node` => `array`
- [ ] `element` => _can't be resolved by dat.GUI_
- [x] `instanceOf(XXX)` => `object`
- [x] `oneOf([...])` => `enum`
- [ ] `oneOfType([...])` => first resolved type
- [x] `arrayOf` => `array`
- [x] `objectOf` => `object`
- [x] `shape` => `object`
- [ ]  `any` => _can't be resolved by dat.GUI_
- [ ]  `custom` => _can't be resolved by dat.GUI_

**Comment by fabienjuif** [comment]
Don't you think that `node` can also be an array of strings ?

**Comment by fabienjuif** [comment]
@bpetetot this issue has to be closed ?
